repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: python
        types: [python]
        require_serial: true
      - id: black
        name: black
        entry: black --diff --check
        language: python
        types: [ python ]
        require_serial: true
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [ python ]
        require_serial: true
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [ python ]
        require_serial: true