"""changed bot settings

Revision ID: 1e69e810a774
Revises: 3de493b66730
Create Date: 2023-12-10 16:48:29.259654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e69e810a774'
down_revision: Union[str, None] = '3de493b66730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('is_posted_in_bot', sa.Boolean(), nullable=False))
    op.drop_constraint('news_bot_post_setting_id_fkey', 'news', type_='foreignkey')
    op.drop_column('news', 'bot_post_setting_id')
    op.add_column('project', sa.Column('is_posted_in_bot', sa.Boolean(), nullable=False))
    op.drop_table('bot_post_setting')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'bot_post_setting',
        sa.Column('is_posted', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint('id', name='bot_post_setting_pkey'),
    )
    op.drop_column('project', 'is_posted_in_bot')
    op.add_column(
        'news', sa.Column('bot_post_setting_id', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_foreign_key(
        'news_bot_post_setting_id_fkey',
        'news',
        'bot_post_setting',
        ['bot_post_setting_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.drop_column('news', 'is_posted_in_bot')
    # ### end Alembic commands ###
