"""renamed press.preview_photo and added foreign key for media.type_id  

Revision ID: 96707e2c88b3
Revises: 9f8e542bcbf7
Create Date: 2023-11-26 13:09:44.764960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96707e2c88b3'
down_revision: Union[str, None] = '9f8e542bcbf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'media', 'media_type', ['type_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('press') as batch_op:
        batch_op.alter_column(column_name='preview_photo', new_column_name='preview_photo_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media', type_='foreignkey')
    with op.batch_alter_table('press') as batch_op:
        batch_op.alter_column(column_name='preview_photo_id', new_column_name='preview_photo')
    # ### end Alembic commands ###
