"""init db

Revision ID: 9f8e542bcbf7
Revises: 
Create Date: 2023-11-06 01:19:03.693346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f8e542bcbf7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_post_setting',
    sa.Column('is_posted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('name', sa.String(length=2048), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=2048), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_type',
    sa.Column('name', sa.String(length=2048), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_category',
    sa.Column('name', sa.String(length=2048), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('electron',
    sa.Column('name', sa.String(length=2048), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('description', sa.String(length=2048), nullable=False),
    sa.Column('text', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('is_posted', sa.Boolean(), nullable=False),
    sa.Column('bot_post_setting_id', sa.Integer(), nullable=False),
    sa.Column('preview_photo', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bot_post_setting_id'], ['bot_post_setting.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['preview_photo'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('painting',
    sa.Column('title', sa.String(length=2048), nullable=False),
    sa.Column('author', sa.String(length=2048), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=False),
    sa.Column('materials', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('is_posted', sa.Boolean(), nullable=False),
    sa.Column('preview_photo', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['preview_photo'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('press',
    sa.Column('title', sa.String(length=2048), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('is_posted', sa.Boolean(), nullable=False),
    sa.Column('preview_photo', sa.Integer(), nullable=False),
    sa.Column('external_link', sa.String(length=2048), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['preview_photo'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('title', sa.String(length=2048), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=False),
    sa.Column('text', sa.String(length=2048), nullable=False),
    sa.Column('project_category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('is_posted', sa.Boolean(), nullable=False),
    sa.Column('preview_photo', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['preview_photo'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_category_id'], ['project_category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_painting',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('painting_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['painting_id'], ['painting.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('media_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_painting')
    op.drop_table('project')
    op.drop_table('press')
    op.drop_table('painting')
    op.drop_table('news')
    op.drop_table('electron')
    op.drop_table('project_category')
    op.drop_table('media_type')
    op.drop_table('media')
    op.drop_table('bot_post_setting')
    # ### end Alembic commands ###
