"""renamed press.preview_photo and changed media.type_id (added foreign key)

Revision ID: a8d9284085eb
Revises: 9f8e542bcbf7
Create Date: 2023-11-25 21:16:03.358110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8d9284085eb'
down_revision: Union[str, None] = '9f8e542bcbf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('electron_photo_id_fkey', 'electron', type_='foreignkey')
    op.create_foreign_key(None, 'electron', 'media', ['photo_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'media', 'media_type', ['type_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('media_painting_media_id_fkey', 'media_painting', type_='foreignkey')
    op.drop_constraint('media_painting_painting_id_fkey', 'media_painting', type_='foreignkey')
    op.create_foreign_key(None, 'media_painting', 'painting', ['painting_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'media_painting', 'media', ['media_id'], ['id'], ondelete='CASCADE')
    op.add_column('news', sa.Column('preview_photo', sa.Integer(), nullable=False))
    op.drop_constraint('news_preview_fkey', 'news', type_='foreignkey')
    op.drop_constraint('news_bot_post_setting_id_fkey', 'news', type_='foreignkey')
    op.create_foreign_key(None, 'news', 'bot_post_setting', ['bot_post_setting_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'news', 'media', ['preview_photo'], ['id'], ondelete='CASCADE')
    op.drop_column('news', 'preview')
    op.add_column('painting', sa.Column('created_at', sa.Date(), nullable=False))
    op.drop_constraint('painting_preview_photo_fkey', 'painting', type_='foreignkey')
    op.create_foreign_key(None, 'painting', 'media', ['preview_photo'], ['id'], ondelete='CASCADE')
    op.drop_column('painting', 'painted_at')
    op.add_column('press', sa.Column('preview_photo_id', sa.Integer(), nullable=False))
    op.drop_constraint('press_preview_photo_fkey', 'press', type_='foreignkey')
    op.create_foreign_key(None, 'press', 'media', ['preview_photo_id'], ['id'], ondelete='CASCADE')
    op.drop_column('press', 'preview_photo')
    op.drop_constraint('project_project_category_id_fkey', 'project', type_='foreignkey')
    op.drop_constraint('project_preview_photo_fkey', 'project', type_='foreignkey')
    op.create_foreign_key(None, 'project', 'project_category', ['project_category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project', 'media', ['preview_photo'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.create_foreign_key('project_preview_photo_fkey', 'project', 'media', ['preview_photo'], ['id'])
    op.create_foreign_key('project_project_category_id_fkey', 'project', 'project_category', ['project_category_id'], ['id'])
    op.add_column('press', sa.Column('preview_photo', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'press', type_='foreignkey')
    op.create_foreign_key('press_preview_photo_fkey', 'press', 'media', ['preview_photo'], ['id'])
    op.drop_column('press', 'preview_photo_id')
    op.add_column('painting', sa.Column('painted_at', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'painting', type_='foreignkey')
    op.create_foreign_key('painting_preview_photo_fkey', 'painting', 'media', ['preview_photo'], ['id'])
    op.drop_column('painting', 'created_at')
    op.add_column('news', sa.Column('preview', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.create_foreign_key('news_bot_post_setting_id_fkey', 'news', 'bot_post_setting', ['bot_post_setting_id'], ['id'])
    op.create_foreign_key('news_preview_fkey', 'news', 'media', ['preview'], ['id'])
    op.drop_column('news', 'preview_photo')
    op.drop_constraint(None, 'media_painting', type_='foreignkey')
    op.drop_constraint(None, 'media_painting', type_='foreignkey')
    op.create_foreign_key('media_painting_painting_id_fkey', 'media_painting', 'painting', ['painting_id'], ['id'])
    op.create_foreign_key('media_painting_media_id_fkey', 'media_painting', 'media', ['media_id'], ['id'])
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_constraint(None, 'electron', type_='foreignkey')
    op.create_foreign_key('electron_photo_id_fkey', 'electron', 'media', ['photo_id'], ['id'])
    # ### end Alembic commands ###
